# Generated by Django 2.0.4 on 2018-10-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
