# Generated by Django 2.0.4 on 2018-10-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_song_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
